"""Rebuild embedded RGB frames: python3 src/animations/halloween/generate.py (Pillow)."""
from pathlib import Path
from PIL import Image, ImageDraw
import math, base64, zlib

ROOT = Path(__file__).resolve().parent
FPS, COUNT = 10, 120
images = {name: Image.open(ROOT / 'assets' / (name + '.png')).convert('RGBA')
          for name in ('pumpkin', 'ghost', 'moon', 'bat')}

def rnd(value):
    return math.floor(value + .5)

def frame(name, t):
    im = Image.new('RGB', (64, 32))
    draw = ImageDraw.Draw(im)
    def rect(x, y, w, h, color):
        x, y = rnd(x), rnd(y)
        draw.rectangle((x, y, x+w-1, y+h-1), fill=color)
    def sprite(asset, x, y, w, h=None):
        image = images[asset].resize((w, h or w), Image.Resampling.NEAREST)
        im.paste(image, (rnd(x), rnd(y)), image)
    if name == 'porch-pals':
        sprite('pumpkin', 2, 3, 28)
        sprite('ghost', 35, 3+rnd(math.sin(t*2)), 26)
        for i, (x, y) in enumerate(((1,27),(30,24),(61,29))):
            rect(x,y,1,1,'#c96517' if math.sin(t*3+i)>0 else '#653006')
    elif name == 'moon-patrol':
        for i, (x,y) in enumerate(((5,4),(22,3),(57,6),(32,11),(60,20))):
            rect(x,y,1,1,'#b7aada' if math.sin(t*2+i)>0 else '#51456e')
        sprite('moon',38,1,23)
        for i in range(9):
            rect(i*8,27,7,5,'#241b34')
            rect(i*8+2,24-i%3,3,8,'#31213e')
        sprite('bat',4+rnd((math.sin(t*.65)+1)*8),9+rnd(math.sin(t*2)*2),28,19)
    elif name == 'something-brewing':
        sprite('pumpkin',36,8,24)
        rect(8,27,15,2,'#a83b1d')
        for i in range(4):
            rect(9+i*4,25-rnd(math.sin(t*6+i)+1),2,4,'#ff9327')
        for args in ((5,16,25,3,'#9560ba'),(7,19,21,7,'#623b85'),
                     (10,26,15,2,'#623b85'),(7,28,3,2,'#9560ba'),
                     (25,28,3,2,'#9560ba'),(8,16,19,2,'#a7e84d'),(9,20,2,4,'#a176c0')):
            rect(*args)
        for i in range(5):
            rect(10+i*3+rnd(math.sin(t*2+i)),15-((t*(3+i%2)+i*3)%14),2,2,
                 '#c8fa70' if i%2 else '#67b62e')
        rect(31,8,1,1,'#bc8edd')
    return im

names = ('porch-pals','moon-patrol','something-brewing')
lines = ['// Generated by generate.py; RGB888 frames compressed with zlib.',
         'export const FRAME_INTERVAL_MS = 100', 'export const FRAME_COUNT = 120',
         'export const WIDTH = 64', 'export const HEIGHT = 32',
         'export const COMPRESSED_FRAMES = {']
for name in names:
    frames = [frame(name, i/FPS) for i in range(COUNT)]
    data = base64.b64encode(zlib.compress(b''.join(f.tobytes() for f in frames),9)).decode()
    lines.append(f"  '{name}': '{data}',")
    # Reviewable animation assets; device playback uses embedded frames, not GIF decoding.
    frames[0].save(ROOT / 'assets' / (name+'.gif'), save_all=True, append_images=frames[1:],
                   duration=100, loop=0, optimize=False, disposal=2)
lines.append('} as const\n')
(ROOT / 'frames.ts').write_text('\n'.join(lines))
print('Generated three 64 × 32 animations, 120 frames each.')
